# Production compose extension
# Usage: docker compose -f docker-compose.yml -f infra/compose/compose.prod.yml up -d

services:
  web:
    restart: unless-stopped
  api:
    restart: unless-stopped
  worker:
    restart: unless-stopped
    deploy:
      replicas: 2
  redis:
    restart: unless-stopped
  ollama:
    restart: unless-stopped
